//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monoflector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monoflector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompositionServices is already initialized..
        /// </summary>
        internal static string CompositionServices_Initialized {
            get {
                return ResourceManager.GetString("CompositionServices_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition Services has not been initialized..
        /// </summary>
        internal static string CompositionServices_NotInitialized {
            get {
                return ResourceManager.GetString("CompositionServices_NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to languageWriterCreator returned a null value..
        /// </summary>
        internal static string LanguageWriterCreator_NullValue {
            get {
                return ResourceManager.GetString("LanguageWriterCreator_NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x64.
        /// </summary>
        internal static string ProcessorArchitecture_Amd64 {
            get {
                return ResourceManager.GetString("ProcessorArchitecture_Amd64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itanium.
        /// </summary>
        internal static string ProcessorArchitecture_IA64 {
            get {
                return ResourceManager.GetString("ProcessorArchitecture_IA64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any CPU.
        /// </summary>
        internal static string ProcessorArchitecture_MSIL {
            get {
                return ResourceManager.GetString("ProcessorArchitecture_MSIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string ProcessorArchitecture_None {
            get {
                return ResourceManager.GetString("ProcessorArchitecture_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x86.
        /// </summary>
        internal static string ProcessorArchitecture_X86 {
            get {
                return ResourceManager.GetString("ProcessorArchitecture_X86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given context is not supported..
        /// </summary>
        internal static string ContextNotSupported {
            get {
                return ResourceManager.GetString("ContextNotSupported", resourceCulture);
            }
        }
    }
}
